### ISSUE TITLE
local_debugger function causes error

### ISSUE THREAD

**Issue by melanietreitinger** [PM84/moodle-tiny_formatting#1]
Hi,

this line in `settings.php` causes an error if the `local_debugger` plugin is not installed:

`\local_debugger\performance\debugger::print_debug('test', 'availFonts', array_values($fontfamilies));`

**Comment by PM84** [comment]
Hi Melanie,

Thanks a lot for the hint! Fixed with https://github.com/PM84/moodle-tiny_formatting/commit/e66cd2ae4b742ddac6076ec639244a6d3f72f4a6
